name: 'Dropbox Uploader'
description: 'Upload files to Dropbox. Support files up to 150 Gb!'
author: 'whalemare'
branding:
  icon: upload-cloud
  color: yellow
inputs:
  accessToken:
    required: true
    description: 'Dropbox access token. Create new one at: https://www.dropbox.com/developers/apps'
  destination:
    required: true
    description: 'Dropbox destination path for uploading. Must be started from /". (ex. "/actions")'
  pattern:
    required: false
    description: 'glob pattern for file (ex. src/**/*)'
  file:
    required: false
    description: 'path to specific file (ex. src/main.ts)'
  partSizeBytes:
    required: false
    description: 'Size of one uploadable chunk in bytes. default: 1024'
  displayProgress:
    required: false
    description: "Display file uploading progress logs. default: false"
outputs:
  files:
    description: "List of files uploaded to Dropbox"
runs:
  using: 'node16'
  main: 'dist/index.js'
